class Surah {
  late String title;
  late String description;

  Surah(
  {required this.title,
    required this.description,
  });
}

List<Surah> surahList = [
  Surah(title:'Al-Fatihah',
    description: 'The Opener | Verse 1',
  ),
  Surah(title:'Al-Baqarah',
    description: 'The Calf | Verse 2',
  ),
  Surah(title:'Al-ee-Imran',
    description: 'The Family of Imraan | Verse 3',
  ),
  Surah(title:'An-Nisa',
    description: 'The Women | Verse 4',
  ),
  Surah(title:'Al-Ma idah',
    description: 'The Table Spread | Verse 5',
  ),
  Surah(title:'Al-An am',
    description: 'The Cattle | Verse 6',
  ),
  Surah(title:'Al-A raf',
    description: 'The Heights | Verse 7',
  ),
  Surah(title:'Al-Anfal',
    description: 'The Spoils of War | Verse 8',
  ),
  Surah(title:'At-Tawbah',
    description: 'The Repentance | Verse 9',
  ),
  Surah(title:'Yunus',
    description: 'Jonah | Verse 10',
  ),
  Surah(title:'Hud',
    description: 'Prophet Hud | Verse 11',
  ),
  Surah(title:'Yusuf',
    description: 'Joseph | Verse 12',
  ),
  Surah(title:'Ar-Ra d',
    description: 'The Thunder | Verse 13',
  ),
  Surah(title:'Ibrahim',
    description: 'Abraham | Verse 14',
  ),
  Surah(title:'Al-Hijr',
    description: 'The Rocky Tract | Verse 15',
  ),
  Surah(title:'An-Nahl',
    description: 'The Bee | Verse 16',
  ),
  Surah(title:'Al-Isra',
    description: 'The Night Journey | Verse 17',
  ),
  Surah(title:'Al-Kahf',
    description: 'The Cave | Verse 18',
  ),
  Surah(title:'Maryam',
    description: 'Mary | Verse 19',
  ),
  Surah(title:'Ta-Ha',
    description: 'Ta-Ha | Verse 20',
  ),
  Surah(title:'Al-Anbiya',
    description: 'The Prophets | Verse 21',
  ),
  Surah(title:'Al-Hajj',
    description: 'The Pilgrimage | Verse 22',
  ),
  Surah(title:'Al-Mu minun',
    description: 'The Believers | Verse 23',
  ),
  Surah(title:'An-Nur',
    description: 'The Light | Verse 24',
  ),
  Surah(title:'Al-Furqan',
    description: 'The Criterion | Verse 25',
  ),
  Surah(title:'Ash-Shu ara',
    description: 'The Poets | Verse 26',
  ),
  Surah(title:'An-Naml',
    description: 'The Ant | Verse 27',
  ),
  Surah(title:'Al-Qasas',
    description: 'The Stories | Verse 28',
  ),
  Surah(title:'Al-Ankabut',
    description: 'The Spider | Verse 29',
  ),
  Surah(title:'Ar-Rum',
    description: 'The Romans | Verse 30',
  ),
  Surah(title:'Luqmaan',
    description: 'Luqman | Verse 31',
  ),
  Surah(title:'As-Sajdah',
    description: 'The Prostration | Verse 32',
  ),
  Surah(title:'Al-Ahzaab',
    description: 'The Combined Forces | Verse 33',
  ),
  Surah(title:'Saba',
    description: 'Sheba | Verse 34',
  ),
  Surah(title:'Faatir',
    description: 'The Originator | Verse 35',
  ),
  Surah(title:'Ya-Sin',
    description: 'Ya-Sin | Verse 36',
  ),
  Surah(title:'As-Saaffaat',
    description: 'Those Who Set The Ranks | Verse 37',
  ),
  Surah(title:'Saad',
    description: 'Sad | Verse 38',
  ),
  Surah(title:'Az-Zumar',
    description: 'The Troops | Verse 39',
  ),
  Surah(title:'Ghafir',
    description: 'The Forgiver | Verse 40',
  ),
  Surah(title:'Fussilat',
    description: 'Explained In Detail | Verse 41',
  ),
  Surah(title:'Ash-Shura',
    description: 'The Consultation | Verse 42',
  ),
  Surah(title:'Az-Zhukhruf',
    description: 'The Ornaments of Gold | Verse 43',
  ),
  Surah(title:'Ad-Dukhaan',
    description: 'The Smoke | Verse 44',
  ),
  Surah(title:'Al-Jaathiyah',
    description: 'The Crouching | Verse 45',
  ),
  Surah(title:'Al-Ahqaaf',
    description: 'The Wind Curved Sandhills | Verse 46',
  ),
  Surah(title:'Muhammad',
    description: 'Muhammad | Verse 47',
  ),
  Surah(title:'Al-Fath',
    description: 'The Victory | Verse 48',
  ),
  Surah(title:'Al-Hujuraat',
    description: 'The Rooms | Verse 49',
  ),
  Surah(title:'Qaaf',
    description: 'Qaf | Verse 50',
  ),
  Surah(title:'Adh-Dhaariyaat',
    description: ' The Winnowing Wind | Verse 51',
  ),
  Surah(title:'At-Toor',
    description: 'The Mount | Verse 52',
  ),
  Surah(title:'An-Najm',
    description: 'The Star | Verse 53',
  ),
  Surah(title:'Al-Qamar',
    description: 'The Moon | Verse 54',
  ),
  Surah(title:'Ar-Rahman',
    description: 'The Most Merciful | Verse 55',
  ),
  Surah(title:'Al-Waqi ah',
    description: 'The Event | Verse 56',
  ),
  Surah(title:'Al-Hadeed',
    description: 'The Iron | Verse 57',
  ),
  Surah(title:'Al-Mujadila',
    description: 'The Pleading Woman | Verse 58',
  ),
  Surah(title:'Al-Hashr',
    description: 'The Exile | Verse 59',
  ),
  Surah(title:'Al-Mumtahanah',
    description: 'She That Is To Be Examined | Verse 60',
  ),
  Surah(title:'As-Saff',
    description: 'The Ranks | Verse 61',
  ),
  Surah(title:'Al-Jumu ah',
    description: 'The Congregation | Verse 62',
  ),
  Surah(title:'Al-Munafiqoon',
    description: 'The Hypocrites | Verse 63',
  ),
  Surah(title:'At-Taghabun',
    description: 'The Mutual Disillusion | Verse 64',
  ),
  Surah(title:'At-Talaq',
    description: 'Divorce | Verse 65',
  ),
  Surah(title:'At-Tahreem',
    description: 'The Prohibition | Verse 66',
  ),
  Surah(title:'Al-Mulk',
    description: 'The Sovereignty | Verse 67',
  ),
  Surah(title:'Al-Qalam',
    description: 'The Pen | Verse 68',
  ),
  Surah(title:'Al-Haaqqa',
    description: 'The Sure Reality | Verse 69',
  ),
  Surah(title:'Al-Ma aarij',
    description: 'The Ascending Stairways | Verse 70',
  ),
  Surah(title:'Nuh',
    description: 'Noah | Verse 71',
  ),
  Surah(title:'Al-Jinn',
    description: 'The Jinn | Verse 72',
  ),
  Surah(title:'Al-Muzzammil',
    description: 'The Enshrouded One | Verse 73',
  ),
  Surah(title:'Al-Muddaththir',
    description: 'The Cloaked One | Verse 74',
  ),
  Surah(title:'Al-Qiyamah',
    description: 'The Day of Resurrection | Verse 75',
  ),
  Surah(title:'Al-Insaan',
    description: 'The Mankind | Verse 76',
  ),
  Surah(title:'Al-Mursalaat',
    description: 'The Emissaries | Verse 77',
  ),
  Surah(title:'An-Naba',
    description: 'The Tidings | Verse 78',
  ),
  Surah(title:'An-Naazi aat',
    description: 'Those Who Drag Forth | Verse 79',
  ),
  Surah(title:'Abasa',
    description: 'He Frowned | Verse 80',
  ),
  Surah(title:'At-Takweer',
    description: 'The Overthrowing | Verse 81',
  ),
  Surah(title:'Al-Infitar',
    description: 'The Cleaving | Verse 82',
  ),
  Surah(title:'At-Taffeef',
    description: 'The Defrauding | Verse 83',
  ),
  Surah(title:'Al-Inshiqaaq',
    description: 'The Sundering, Splitting Open | Verse 84',
  ),
  Surah(title:'Al-Burooj',
    description: 'The Mansions Of The Stars | Verse 85',
  ),
  Surah(title:'At-Taariq',
    description: 'The Nightcomer | Verse 86',
  ),
  Surah(title:'Al-A la',
    description: 'The Most High | Verse 87',
  ),
  Surah(title:'Al-Ghaashiyah',
    description: 'The Overwhelming | Verse 88',
  ),
  Surah(title:'Al-Fajr',
    description: 'The Dawn | Verse 89',
  ),
  Surah(title:'Al-Balad',
    description: 'The City | Verse 90',
  ),
  Surah(title:'Ash-Shams',
    description: 'The Sun | Verse 91',
  ),
  Surah(title:'Al-Layl',
    description: 'The Night | Verse 92',
  ),
  Surah(title:'Ad-Dhuha',
    description: 'The Morning Hours | Verse 93',
  ),
  Surah(title:'Ash-Sharh',
    description: 'The Relief | Verse 94',
  ),
  Surah(title:'At-Tin',
    description: 'The Fig | Verse 95',
  ),
  Surah(title:'Al-Alaq',
    description: 'The Clot | Verse 96',
  ),
  Surah(title:'Al-Qadr',
    description: 'The Power | Verse 97',
  ),
  Surah(title:'Al-Bayyinahh',
    description: 'The Clear Proof | Verse 98',
  ),
  Surah(title:'Az-Zalzalah',
    description: 'The Earthquake | Verse 99',
  ),
  Surah(title:'Al- Aadiyat',
    description: 'The Courser | Verse 100',
  ),
  Surah(title:'Al-Qaari ah',
    description: 'The Calamity | Verse 101',
  ),
  Surah(title:'At-Takaathur',
    description: 'The Rivalry For World Increase | Verse 102',
  ),
  Surah(title:'Al-Asr',
    description: 'The Declining Day | Verse 103',
  ),
  Surah(title:'Al-Humazah',
    description: 'The Traducer | Verse 104',
  ),
  Surah(title:'Al-Feel',
    description: 'The Elephant | Verse 105',
  ),
  Surah(title:'Quraysh',
    description: 'The Quraysh | Verse 106',
  ),
  Surah(title:'Al-Maa oon',
    description: 'The Small Kindnesses | Verse 107',
  ),
  Surah(title:'Al-Kawthar',
    description: 'The Abundance | Verse 108',
  ),
  Surah(title:'Al-Kafirun',
    description: 'The Disbelievers | Verse 109',
  ),
  Surah(title:'An-Nasr',
    description: 'Divine Support | Verse 110',
  ),
  Surah(title:'Al-Masad',
    description: 'The Palm Fibre | Verse 111',
  ),
  Surah(title:'Al-Ikhlas',
    description: 'The Sincerity | Verse 112',
  ),
  Surah(title:'Al-Falaq',
    description: 'The Daybreak | Verse 113',
  ),
  Surah(title:'An-Naas',
    description: 'Mankind | Verse 114',
  ),
];